server:
  host: '127.0.0.1'
  port: 7777

browser:
  bin: /usr/bin/chromium
  globalTimeout: 10

victims:
  2:
    server_url: 'http://127.0.0.1:3000'
    client_url: 'http://127.0.0.1:3001'
    username: 'admin'
    password: 'admin'
  3:
    server_url: 'http://127.0.0.1:3000'
    client_url: 'http://127.0.0.1:3001'
    username: 'admin'
    password: 'admin'
