run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - asasalint # warns about passing []any to func(...any) without expanding it
    - asciicheck # non ascii symbols
    - bidichk # dangerous unicode sequences
    - bodyclose # unclosed http bodies
    - copyloopvar # copying loop variables
    - dogsled # too many blank identifiers in assignments
    - dupword # duplicate words
    - durationcheck # multiplying two durations
    - errcheck # unchecked errors
    - errchkjson # invalid types passed to json encoder
    - ginkgolinter # ginkgo and gomega
    - goconst # strings that can be replaced by constants
    - gocritic # bugs, performance, style (we could add custom ones to this one)
    - gofmt # warns about incorrect use of fmt functions
    - goimports # import formatting
    - goprintffuncname # printft-like functions should be named with f at the end
    - gosec # potential security problems
    - gosimple # simplify code
    - govet # basically 'go vet'
    - importas # consistent import aliases
    - ineffassign # ineffectual assignments
    - loggercheck # check for even key/value pairs in logger calls
    - misspell # spelling
    - nakedret # naked returns (named return parameters and an empty return)
    - nilerr # returning nil after checking err is not nil
    - noctx # http requests without context.Context
    - nolintlint # badly formatted nolint directives
    - nosprintfhostport # using sprintf to construct host:port in a URL
    - prealloc # suggest preallocating slices
    - predeclared # shadowing predeclared identifiers
    - revive # better version of golint
    - staticcheck # some of staticcheck's rules
    - stylecheck # another replacement for golint
    - tenv # using os.Setenv instead of t.Setenv in tests
    - thelper # test helpers not starting with t.Helper()
    - unconvert # unnecessary type conversions
    - unparam # unused function parameters
    - unused # unused constants, variables,functions, types
    - whitespace # unnecessary newlines
