-- lab00
CREATE USER 'server00'@'%' IDENTIFIED BY '531hTODRLhYtTSNgoW82EbPX7eG3KdBS';
CREATE DATABASE server00;
GRANT ALL PRIVILEGES ON server00.* TO 'server00'@'%';
CREATE USER 'client00'@'%' IDENTIFIED BY 'gpMbgO8SktX83uHbQTweKNbJrA7kmR7c';
CREATE DATABASE client00;
GRANT ALL PRIVILEGES ON client00.* TO 'client00'@'%';

-- lab01
CREATE USER 'server01'@'%' IDENTIFIED BY '8EvEu6pqwwDE4ydtokfs2e9y7Ijxn4UQx';
CREATE DATABASE server01;
GRANT ALL PRIVILEGES ON server01.* TO 'server01'@'%';
CREATE USER 'client01'@'%' IDENTIFIED BY 'p6yJwCU9H1p5sCIZZn2qj1sATWyDK6N1G';
CREATE DATABASE client01;
GRANT ALL PRIVILEGES ON client01.* TO 'client01'@'%';

-- lab02
CREATE USER 'server02'@'%' IDENTIFIED BY '3OdAH5nDCypvVQ60infxhXZjOMhZKcA7Y';
CREATE DATABASE server02;
GRANT ALL PRIVILEGES ON server02.* TO 'server02'@'%';
CREATE USER 'client02'@'%' IDENTIFIED BY '8WLbZdzlghcne7aY1rm5LuF3jQ3uYfH7Q';
CREATE DATABASE client02;
GRANT ALL PRIVILEGES ON client02.* TO 'client02'@'%';

-- lab03
CREATE USER 'server03'@'%' IDENTIFIED BY 'wpSoiDJw8WS314VQnFr8lSIb6B918xUx0';
CREATE DATABASE server03;
GRANT ALL PRIVILEGES ON server03.* TO 'server03'@'%';
CREATE USER 'client03'@'%' IDENTIFIED BY 'v94Rm5pAIwO6CTCIazp8XFUCGey0Waiei';
CREATE DATABASE client03;
GRANT ALL PRIVILEGES ON client03.* TO 'client03'@'%';

-- lab04
CREATE USER 'server04'@'%' IDENTIFIED BY '1qx6Ht4qi8Tf75883tTjrEiFvcHAg5fWQ';
CREATE DATABASE server04;
GRANT ALL PRIVILEGES ON server04.* TO 'server04'@'%';
CREATE USER 'client04'@'%' IDENTIFIED BY 'vmsrOk7Voq3LyKucmXnkWVLQvfoU9gUOy';
CREATE DATABASE client04;
GRANT ALL PRIVILEGES ON client04.* TO 'client04'@'%';

-- lab05
CREATE USER 'server05'@'%' IDENTIFIED BY 'SThDcdIfi5L6hlHgjwghS2oRbQyJN4fhL';
CREATE DATABASE server05;
GRANT ALL PRIVILEGES ON server05.* TO 'server05'@'%';
CREATE USER 'client05'@'%' IDENTIFIED BY 'VOTezxlC5myozyn2wy0UfVLfVNbGqjgfy';
CREATE DATABASE client05;
GRANT ALL PRIVILEGES ON client05.* TO 'client05'@'%';
